name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pylint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.10" ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Pylint module
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint==2.14.1
        pip install pylint_runner==0.6.0

    - name: Run Pylint
      run: |
        pylint_runner -d C -d R --verbose

  black_lint:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        python-version: [ "3.10" ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Black lint module
      run: |
        python -m pip install --upgrade pip
        pip install black==22.6.0
    - name: Run Lint check
      run: |
        black . --config pyproject.toml --check
